name: PROJECT_NAME

recipe: drupal8

config:
  webroot: docroot
  php: '7.2'
  drush: '*'
  xdebug: true
  conf: 
    php: .vscode/php.ini

services:
  database:
    creds:
      user: drupal
      password: drupal
      database: drupal

tooling:
  drush:
    service: appserver
    cmd: /app/vendor/drush/drush/drush
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
